version: '3.2'

services: 
  app:
    build:
      dockerfile: Dockerfile
      context: .
    restart: unless-stopped
    volumes:
      - .:/app/
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - web
    environment:
      NODE_ENV: production
      TZ: America/Bogota
      VIRTUAL_HOST: pay.backsoul.online
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: pay.backsoul.online
      LETSENCRYPT_EMAIL: danielsarmientoenterprise@gmail.com

networks:
  web:
    external: true