services:
  # used as base for all services
  test: &defaults
    build:
      context: .
      target: builder
    working_dir: /app/
    command: go test -v ./...
    volumes:
      - .:/app/

  # include all information in test and
  # add the command to run
  # app:
  #   <<: *defaults
  #   command: go run main.go bot -p twitch -c jorllinio_11 --proxies 5
  #   volumes:
  #     - .:/app/
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  
  # ondetah:
  #   <<: *defaults
  #   command: go run main.go ondetah -t 44567663268081587803
  #   volumes:
  #     - .:/app/
  #     - /var/run/docker.sock:/tmp/docker.sock:ro

  api:
    <<: *defaults
    command: go run main.go api 
    volumes:
      - .:/app/
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      NODE_ENV: production
      TZ: America/Bogota
      VIRTUAL_HOST: ondetah.backsoul.com.co
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: ondetah.backsoul.com.co
      LETSENCRYPT_EMAIL: danielsarmientoenterprise@gmail.com