services:
  # used as base for all services
  test: &defaults
    build:
      context: .
      target: builder
    working_dir: /app/
    command: go test -v ./...
    volumes:
      - .:/app/

  # include all information in test and
  # add the command to run
  app:
    <<: *defaults
    command: go run main.go bot -p twitch -c jjosuplayss --proxies 100
    volumes:
      - .:/app/
      - /var/run/docker.sock:/tmp/docker.sock:ro